= {lab_name}
include::_attributes.adoc[]

== {ic} の概要

この {ic-lab} では、さまざまな AI/ML テクノロジを組み合わせて、ビジネス上の問題に対する価値あるソリューションを生み出す方法を説明します。

このラボに含まれる情報、コード、モデル、および様々なテクニックは、最初のプロトタイプをどのように組み立てるかを示したものです。これは、最終的なビジネス要件に対処するための決定的な方法ではありません。

==  免責事項

この {ic-lab} は、お客様が {rhoai}  を使用して構築できるものの例です。{rhoai}  には、保険金請求処理に関連する特定の機能はありません。

この {ic-lab} では、大規模言語モデル (LLM) と画像処理モデルを使用します。これらのモデルはオープンソースで提供されており、 {rhoai} 製品には含まれていません。
これらのモデルの品質は、プロトタイプには十分です。本番環境で使用する適切なモデルを選択することは、多くの実験と調整を必要とする複雑な作業です。この {ic-lab} では、この側面は取り上げません。

== タイムテーブル

以下は、本日のワークショップのタイムテーブルです。所要時間は目安なのでご自身のペースで進めて下さい。
[width="90%",cols="3,^2,^2,10",options="header"]
|=========================================================
| 名前 | 所要時間 | タイプ | 説明

| 背景 | 5 | プレゼンテーション
a|- ワークショップの背景とゴールについて説明します。
- 全体的なユーザー エクスペリエンスと基礎となるアーキテクチャについて説明します。

| 接続とセットアップ | 5 | ハンズオン
a|- 参加者が自身のワークショップ環境に接続します。
- 環境の健全性の検証を行います。

|LLM |20 | ハンズオン
a|- 請求文書の要約
- 感情の抽出
- モデル比較と選択
- パイプラインによる全性チェック
- プロンプト エンジニアリング（オプション）

| 画像処理 | 20 | ハンズオン
a|- 車の画像認識
- モデルの再トレーニング
- モデルのサービング

| Web アプリ | 20 | ハンズオン
a|- GitOpsによるサンプルアプリケーションのデプロイ
- RAG


|=========================================================


== Contribution

このプロジェクトへの貢献にご興味がある場合は、この GitHub リポジトリを参照してください: https://github.com/team-ohc-jp-place/parasol-insurance/tree/translation-jp[https://github.com/team-ohc-jp-place/parasol-insurance/tree/translation-jp,window=_blank]
